// --- Data Definitions ---
const INITIAL_TASKS = [
  {
    id: "t1",
    name: "Watch movies/series/youtube videos",
    targetTime: null,
    targetStr: "Unlimited",
    icon: "film",
    colorClass: "bg-indigo-50 text-indigo-600",
    desc: "Relax and enjoy visual content while staying updated with trends, entertainment, and useful ideas.",
  },
  {
    id: "t2",
    name: "Read technological articles/news/documentation",
    targetTime: 30,
    targetStr: "30 min",
    icon: "book-open",
    colorClass: "bg-blue-50 text-blue-600",
    desc: "Stay updated with technology trends, improve knowledge, and sharpen problem-solving skills.",
  },
  {
    id: "t3",
    name: "Explore with AI",
    targetTime: 30,
    targetStr: "30 min",
    icon: "bot",
    colorClass: "bg-sky-50 text-sky-600",
    desc: "Ask questions, explore ideas, and get help with learning, work, or daily challenges.",
  },
  {
    id: "t4",
    name: "Duolingo",
    targetTime: 30,
    targetStr: "30 min",
    icon: "graduation-cap",
    colorClass: "bg-emerald-50 text-emerald-600",
    desc: "Maintain a consistent learning habit with short and engaging lessons every day.",
  },
  {
    id: "t5",
    name: "Listen podcast",
    targetTime: 20,
    targetStr: "20 min",
    icon: "headphones",
    colorClass: "bg-fuchsia-50 text-fuchsia-600",
    desc: "Learn new ideas, stories, and insights while relaxing or doing other activities.",
  },
  {
    id: "t6",
    name: "Self talk in front of camera",
    targetTime: 10,
    targetStr: "5-10 min",
    icon: "video",
    colorClass: "bg-orange-50 text-orange-600",
    desc: "Record yourself sharing thoughts, reflecting on the day, or practicing confidence on camera.",
  },
  {
    id: "t7",
    name: "Call family, frields and relatives",
    targetTime: null,
    targetStr: "Sometimes",
    icon: "phone-call",
    colorClass: "bg-purple-50 text-purple-600",
    desc: "Connect with friends or colleagues through meaningful conversations and stay socially active.",
  },
];

const AVAILABLE_ICONS = [
  "star",
  "zap",
  "compass",
  "book",
  "coffee",
  "sun",
  "heart",
  "moon",
  "music",
  "smile",
  "pen-tool",
  "target",
  "flag",
  "code",
  "film",
  "book-open",
  "bot",
  "graduation-cap",
  "headphones",
  "video",
  "phone-call",
  // Goals & Productivity
  "trending-up",
  "check-circle",
  "award",
  "medal",
  "flame",
  "activity",
  "crosshair",
  "dumbbell",
  "calendar",
  // Students
  "pencil",
  "edit",
  "library",
  "backpack",
  "microscope",
  "calculator",
  "book-open-check",
  "file-text",
  "brain",
  // Office Workers
  "briefcase",
  "monitor",
  "keyboard",
  "mail",
  "pie-chart",
  "bar-chart",
  "presentation",
  "users",
  "file-spreadsheet",
  "inbox",
  "printer",
  "wallet",
  // Hobbies & Lifestyle
  "camera",
  "palette",
  "shopping-bag",
  "gift",
  "plane",
  "map",
  "globe",
  "watch",
  // Coding & Tech
  "terminal",
  "database",
  "cpu",
  "server",
  "wifi",
  "smartphone",
  "laptop",
  // Organization
  "archive",
  "folder",
  "tag",
  "clipboard",
  "list",
  "check-square",
  // Miscellaneous
  "key",
  "lock",
  "anchor",
  "bell",
  "clock",
  "cloud",
  "droplet",
  "lightbulb",
  "mouse",
  "shield",
  "truck",
  "umbrella",
];

// --- Achievement Definitions ---
const ACHIEVEMENTS = [
  // Daily milestones
  {
    id: "daily_all_done",
    type: "daily",
    label: "🏆 All Tasks Done!",
    desc: "You completed every task today!",
    check: (stats) =>
      stats.todayCompleted > 0 && stats.todayCompleted === stats.todayTotal,
  },
  {
    id: "daily_100",
    type: "daily",
    label: "💪 100 Min Today!",
    desc: "You hit 100 minutes of practice!",
    check: (stats) => stats.todayTime >= 100,
  },
  {
    id: "daily_200",
    type: "daily",
    label: "🔥 200 Min Today!",
    desc: "An incredible 200 minutes today!",
    check: (stats) => stats.todayTime >= 200,
  },
  {
    id: "daily_300",
    type: "daily",
    label: "⚡ 300 Min Today!",
    desc: "Legendary 300 minutes in a single day!",
    check: (stats) => stats.todayTime >= 300,
  },
  // Weekly milestones
  {
    id: "weekly_300",
    type: "weekly",
    label: "📅 300 Min This Week!",
    desc: "Great weekly consistency!",
    check: (stats) => stats.weeklyTime >= 300,
  },
  {
    id: "weekly_500",
    type: "weekly",
    label: "🚀 500 Min This Week!",
    desc: "Half a thousand minutes this week!",
    check: (stats) => stats.weeklyTime >= 500,
  },
  {
    id: "weekly_700",
    type: "weekly",
    label: "🌟 700 Min This Week!",
    desc: "Amazing weekly dedication!",
    check: (stats) => stats.weeklyTime >= 700,
  },
  {
    id: "weekly_1000",
    type: "weekly",
    label: "👑 1000 Min This Week!",
    desc: "A thousand minutes of pure effort!",
    check: (stats) => stats.weeklyTime >= 1000,
  },
  // Monthly milestones
  {
    id: "monthly_1000",
    type: "monthly",
    label: "🎯 1K Min This Month!",
    desc: "1,000 minutes this month!",
    check: (stats) => stats.monthlyTime >= 1000,
  },
  {
    id: "monthly_2000",
    type: "monthly",
    label: "💎 2K Min This Month!",
    desc: "2,000 minutes of mastery!",
    check: (stats) => stats.monthlyTime >= 2000,
  },
  {
    id: "monthly_3000",
    type: "monthly",
    label: "🏅 3K Min This Month!",
    desc: "3,000 minutes — unstoppable!",
    check: (stats) => stats.monthlyTime >= 3000,
  },
  {
    id: "monthly_5000",
    type: "monthly",
    label: "🌈 5K Min This Month!",
    desc: "5,000 minutes — you're a legend!",
    check: (stats) => stats.monthlyTime >= 5000,
  },
];
