import { ITask } from "@/models";

export const INITIAL_TASKS: readonly ITask[] = [
  {
    id: "t1",
    name: "Watch movies/series/youtube videos",
    targetTime: null,
    targetStr: "Unlimited",
    icon: "film",
    colorClass: "bg-indigo-50 text-indigo-600",
    desc: "Relax and enjoy visual content while staying updated with trends, entertainment, and useful ideas.",
    repeatDaily: true,
  },
  {
    id: "t2",
    name: "Read technological articles/news/documentation",
    targetTime: 30,
    targetStr: "30 min",
    icon: "book-open",
    colorClass: "bg-blue-50 text-blue-600",
    desc: "Stay updated with technology trends, improve knowledge, and sharpen problem-solving skills.",
    repeatDaily: true,
  },
  {
    id: "t3",
    name: "Explore with AI",
    targetTime: 30,
    targetStr: "30 min",
    icon: "bot",
    colorClass: "bg-sky-50 text-sky-600",
    desc: "Ask questions, explore ideas, and get help with learning, work, or daily challenges.",
    repeatDaily: false,
  },
  {
    id: "t4",
    name: "Duolingo",
    targetTime: 30,
    targetStr: "30 min",
    icon: "graduation-cap",
    colorClass: "bg-emerald-50 text-emerald-600",
    desc: "Maintain a consistent learning habit with short and engaging lessons every day.",
    repeatDaily: false,
  },
  {
    id: "t5",
    name: "Listen podcast",
    targetTime: 20,
    targetStr: "20 min",
    icon: "headphones",
    colorClass: "bg-fuchsia-50 text-fuchsia-600",
    desc: "Learn new ideas, stories, and insights while relaxing or doing other activities.",
    repeatDaily: true,
  },
  {
    id: "t6",
    name: "Self talk in front of camera",
    targetTime: 10,
    targetStr: "5-10 min",
    icon: "video",
    colorClass: "bg-orange-50 text-orange-600",
    desc: "Record yourself sharing thoughts, reflecting on the day, or practicing confidence on camera.",
    repeatDaily: false,
  },
  {
    id: "t7",
    name: "Call family, friends and relatives",
    targetTime: null,
    targetStr: "Sometimes",
    icon: "phone-call",
    colorClass: "bg-purple-50 text-purple-600",
    desc: "Connect with friends or colleagues through meaningful conversations and stay socially active.",
    repeatDaily: true,
  },
];

export const AVAILABLE_ICONS: readonly string[] = [
  "star",
  "zap",
  "compass",
  "book",
  "coffee",
  "sun",
  "heart",
  "moon",
  "music",
  "smile",
  "pen-tool",
  "target",
  "flag",
  "code",
  "film",
  "book-open",
  "bot",
  "graduation-cap",
  "headphones",
  "video",
  "phone-call",
  "trending-up",
  "check-circle",
  "award",
  "medal",
  "flame",
  "activity",
  "crosshair",
  "dumbbell",
  "calendar",
  "pencil",
  "edit",
  "library",
  "backpack",
  "microscope",
  "calculator",
  "book-open-check",
  "file-text",
  "brain",
  "briefcase",
  "monitor",
  "keyboard",
  "mail",
  "pie-chart",
  "bar-chart",
  "presentation",
  "users",
  "file-spreadsheet",
  "inbox",
  "printer",
  "wallet",
  "camera",
  "palette",
  "shopping-bag",
  "gift",
  "plane",
  "map",
  "globe",
  "watch",
  "terminal",
  "database",
  "cpu",
  "server",
  "wifi",
  "smartphone",
  "laptop",
  "archive",
  "folder",
  "tag",
  "clipboard",
  "list",
  "check-square",
  "key",
  "lock",
  "anchor",
  "bell",
  "clock",
  "cloud",
  "droplet",
  "lightbulb",
  "mouse",
  "shield",
  "truck",
  "umbrella",
  "plus",
];
